name: scheduled health check

on:
  schedule:
    - cron:  '30 6/12 * * *'
  workflow_dispatch:
  
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-exercise.onrender.com/health
          max-attempts: 3
          retry-delay: 30s
      - name: Inform Discord in case of failure
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          text: Health check failed!
          description: Health check of https://full-stack-open-pokedex-exercise.onrender.com/ by justenlu failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
